# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]
  #push:
  #  branches: 
  #    - master
  schedule:
    - cron: 0 18 * * 1,5
  watch:
    types: [started]
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Set SSH Environment
      run: |
        git config --global user.email "cqc@cuiqingcai.com"
        git config --global user.name "Germey"
    - name: Sync Docs of Gerapy
      env:
        IBM_GIT_RES: ${{ secrets.IBM_GIT_RES }}
      run: |
        cd /tmp
        git clone $IBM_GIT_RES
        cd ./tz/test
        date > git-auto.txt
        git commit -a -m "git auto commit"
        git push origin --force
